-- MySQL Script generated by MySQL Workbench
-- Tue Oct 16 17:25:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`bodega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bodega` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bodega` (
  `id_bodega` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `responsable_bodega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_bodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cab_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cab_factura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cab_factura` (
  `num_factura` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`num_factura`),
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL,
  `ssn_cliente` INT NOT NULL,
  `tipo_ssn` VARCHAR(45) NOT NULL,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `apellido_cliente` VARCHAR(45) NOT NULL,
  `direccion_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`det_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`det_factura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`det_factura` (
  `num_factura` INT NOT NULL,
  `tipo_impuesto` VARCHAR(45) NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad_producto` INT NOT NULL,
  `unidad_medida` VARCHAR(45) NOT NULL,
  `valor_impuesto` INT NOT NULL,
  `subtotal` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `id_bodega` INT NOT NULL,
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `id_bodega_idx` (`id_bodega` ASC) VISIBLE,
  INDEX `unidad_medida_idx` (`unidad_medida` ASC) VISIBLE,
  INDEX `num_factura_idx` (`num_factura` ASC) VISIBLE,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_bodega`
    FOREIGN KEY (`id_bodega`)
    REFERENCES `mydb`.`bodega` (`id_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `unidad_medida`
    FOREIGN KEY (`unidad_medida`)
    REFERENCES `mydb`.`medida` (`unidad_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `num_factura`
    FOREIGN KEY (`num_factura`)
    REFERENCES `mydb`.`cab_factura` (`num_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facturas_ingresadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`facturas_ingresadas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`facturas_ingresadas` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `num_factura` INT NOT NULL,
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `num_factura_idx` (`num_factura` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `num_factura`
    FOREIGN KEY (`num_factura`)
    REFERENCES `mydb`.`cab_factura` (`num_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medida` (
  `unidad_medida` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unidad_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimiento_inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movimiento_inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movimiento_inventario` (
  `num_movimiento` INT NOT NULL,
  `id_bodega` INT NOT NULL,
  `tipo_movimiento` VARCHAR(45) NOT NULL,
  `costo` FLOAT NOT NULL,
  `cantidad_inventario` INT NOT NULL,
  `responsable_inventario` VARCHAR(45) NOT NULL,
  `referencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_movimiento`),
  INDEX `id_bodega_idx` (`id_bodega` ASC) VISIBLE,
  CONSTRAINT `id_bodega`
    FOREIGN KEY (`id_bodega`)
    REFERENCES `mydb`.`bodega` (`id_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id_producto` INT NOT NULL,
  `descripcion_producto` VARCHAR(60) NOT NULL,
  `precio_producto` FLOAT NOT NULL,
  `unidad_medida` VARCHAR(45) NOT NULL,
  `estado_producto` TINYINT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `unidad_medida_idx` (`unidad_medida` ASC) VISIBLE,
  CONSTRAINT `unidad_medida`
    FOREIGN KEY (`unidad_medida`)
    REFERENCES `mydb`.`medida` (`unidad_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `apellido_usuario` VARCHAR(45) NOT NULL,
  `contraseña_usuario` VARCHAR(45) NOT NULL,
  `edad_usuario` INT NOT NULL,
  `correo_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`, `correo_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
