/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class jugadores extends javax.swing.JFrame {

    /**
     * Creates new form jugadores
     */
    public static int jugadores = 1;

    public int getJugadores() {
        return jugadores;
    }

    public jugadores() {

        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cards.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btn3Jugadores = new javax.swing.JToggleButton();
        btn4Jugadores = new javax.swing.JToggleButton();
        btn2Jugadores = new javax.swing.JToggleButton();
        btnMultijugador = new javax.swing.JToggleButton();
        btnSolitario = new javax.swing.JToggleButton();
        btnEmpezarJuego = new javax.swing.JButton();
        textoAyuda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 230, -1));

        btnRegresar.setText("Regresar a las instrucciones");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 230, -1));

        btn3Jugadores.setText("3 Jugadores");
        btn3Jugadores.setEnabled(false);
        btn3Jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3JugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btn3Jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 150, -1));

        btn4Jugadores.setText("4 Jugadores");
        btn4Jugadores.setEnabled(false);
        btn4Jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4JugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btn4Jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 150, -1));

        btn2Jugadores.setText("2 Jugadores");
        btn2Jugadores.setEnabled(false);
        btn2Jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2JugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btn2Jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 150, -1));

        btnMultijugador.setText("Multijugador");
        btnMultijugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultijugadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultijugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 150, 30));

        btnSolitario.setText("Solitario");
        btnSolitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolitarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 30));

        btnEmpezarJuego.setText("Empezar el Juego");
        btnEmpezarJuego.setEnabled(false);
        btnEmpezarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpezarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 170, 50));
        getContentPane().add(textoAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 280, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione los Jugadores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 280, 30));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\InterfasesJava\\img\\Interfases\\fondo.jpg")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMultijugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultijugadorActionPerformed

        if (btnMultijugador.isSelected()) {
            btnEmpezarJuego.setEnabled(false);
            btnSolitario.setSelected(false);
            btn2Jugadores.setEnabled(true);
            btn3Jugadores.setEnabled(true);
            btn4Jugadores.setEnabled(true);

        } else {
            btnEmpezarJuego.setEnabled(false);
        }


    }//GEN-LAST:event_btnMultijugadorActionPerformed

    private void btnSolitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolitarioActionPerformed

        jugadores = 1;
        if (btnSolitario.isSelected()) {

            btn2Jugadores.setEnabled(false);
            btn3Jugadores.setEnabled(false);
            btn4Jugadores.setEnabled(false);
            btn2Jugadores.setSelected(false);
            btn4Jugadores.setSelected(false);
            btn3Jugadores.setSelected(false);
            btnEmpezarJuego.setEnabled(true);
            btnMultijugador.setSelected(false);
        } else {
            btnEmpezarJuego.setEnabled(false);
        }


    }//GEN-LAST:event_btnSolitarioActionPerformed

    private void btnEmpezarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarJuegoActionPerformed
        Juego paso = new Juego();
        paso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpezarJuegoActionPerformed

    private void btn2JugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2JugadoresActionPerformed

        jugadores = 2;
        if (btn2Jugadores.isSelected()) {

            btn3Jugadores.setSelected(false);
            btn4Jugadores.setSelected(false);
            btnEmpezarJuego.setEnabled(true);
        } else {
            btnEmpezarJuego.setEnabled(false);
            jugadores = 1;
        }


    }//GEN-LAST:event_btn2JugadoresActionPerformed

    private void btn3JugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3JugadoresActionPerformed

        jugadores = 3;
        if (btn3Jugadores.isSelected()) {

            btn2Jugadores.setSelected(false);
            btn4Jugadores.setSelected(false);
            btnEmpezarJuego.setEnabled(true);
        } else {
            btnEmpezarJuego.setEnabled(false);
            jugadores = 1;
        }

    }//GEN-LAST:event_btn3JugadoresActionPerformed

    private void btn4JugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4JugadoresActionPerformed

        jugadores = 4;
        if (btn4Jugadores.isSelected()) {

            btn2Jugadores.setSelected(false);
            btn3Jugadores.setSelected(false);
            btnEmpezarJuego.setEnabled(true);
        } else {
            btnEmpezarJuego.setEnabled(false);
            jugadores = 1;
        }
    }//GEN-LAST:event_btn4JugadoresActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
        ventanaDeJuego paso = new ventanaDeJuego();
        
        paso.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jugadores().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn2Jugadores;
    private javax.swing.JToggleButton btn3Jugadores;
    private javax.swing.JToggleButton btn4Jugadores;
    private javax.swing.JButton btnEmpezarJuego;
    private javax.swing.JToggleButton btnMultijugador;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton btnSolitario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textoAyuda;
    // End of variables declaration//GEN-END:variables
}
